### ISSUE TITLE
RDTSC real timing check

### ISSUE THREAD

**Issue by redactedontop** [NotRequiem/VMAware#136]
You honestly should check the actual cpu timings as stuff like [this guide](https://github.com/A1exxander/KVM-Spoofing)'s VM exit bypass returns a static value. It explains better than me. Full guide's result: https://user-images.githubusercontent.com/88210134/130307422-b019ebcb-8c9f-4f0c-a028-1b0270475a2b.png

**Comment by kernelwernel** [comment]
RDTSC is disabled by default because of:
1. how easy it is to bypass on KVM, which i've been aware of this issue
2. because it can return false positives on host system in rare instances, which i've experienced a few times

So in reality there's no much I can do about it, and i'd argue it's one of the worser categories of techniques in my mind tbh

I appreciate the guide you've shared and I already have a few ideas for a few KVM detections from that repo, thanks man :+1:

**Comment by redactedontop** [comment]
No worries bro, glad I could help. It does return a false positive on me haha.. the anti-bypass I suggested is just an idea.
