### ISSUE TITLE
Windows BareMetal detected 100%

### ISSUE THREAD

**Issue by Serpensin** [NotRequiem/VMAware#75]
Hello.
I just compiled and tested VMAware. On my baremetal Windows11 machine, it detects "Microsoft Virtual PC/Hyper-V" with a 100% certainty.

Here are the checks, that flagged "detected":
• Checking 0x4 leaf of VMID...
• Checking RDTSC VMEXIT...
• Checking VM directories...
• Checking MMX instruction set...

I have HyperV, VM-Platform, Windows-Sandbox and WSL enabled. I also have docker desktop installed, if that helps.

**Comment by kernelwernel** [comment]
> Hello. I just compiled and tested VMAware. On my baremetal Windows11 machine, it detects "Microsoft Virtual PC/Hyper-V" with a 100% certainty.
> 
> Here are the checks, that flagged "detected": • Checking 0x4 leaf of VMID... • Checking RDTSC VMEXIT... • Checking VM directories... • Checking MMX instruction set...
> 
> I have HyperV, VM-Platform, Windows-Sandbox and WSL enabled. I also have docker desktop installed, if that helps.

Windows 11 has an obscure feature where applications are run inside Hyper-V by default, even on baremetal (only if Hyper-V is enabled). I've had people tell me this issue before but there's really nothing I can do, because it is in fact running inside a VM. 

I'll update the CLI code so it has a note that addresses this confusing Hyper-V thing, but yeah I hope this makes it clearer why you got that result.


**EDIT:** I was spitting out bullshit apparently. Hyper-V doesn't do what i just described above. The result is due to Hyper-V leaving out artifacts of its VM to the host, making it seem like the host is a VM itself. A workaround solution has been designed in the 1.8 version though.

**Comment by kernelwernel** [comment]
**NOTE:** this has been fixed in the latest [1.5 release](https://github.com/kernelwernel/VMAware/releases/tag/v1.5), results that detect the Hyper-V brand will assuming it's using default virtualisation on a host OS, discarding the result and thus outputting that it's NOT running in a VM.
